Repository web3swift-team/web3swift, pull requests merged in 2022-11, with the labels that each got.

#661 Add support for multiple contract methods with same name
  Sources/Core/Contract/ContractProtocol.swift
Labels: bug

#664 fix!: web3 error output fix
  Sources/Core/Web3Error/Web3Error.swift
  Tests/web3swiftTests/localTests/Web3ErrorTests.swift
Labels: enhancement

#665 Fix validation in SPI package list
  Package.swift
Labels: bug, linux
